name: Manual Deploy

# Started from GH Docs
# https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-google-kubernetes-engine

# REQUIRED REPO SECRETS
#   - GCP_CREDENTIALS or AWS_ACCESS_KEY/SECRET
#   - CLUSTER_PREFIX
#   - APOLLO_KEY
#   - APOLLO_GRAPH_ID

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Git ref to deploy"
        type: string
        required: true
        default: main
      environment:
        description: "Target environment"
        type: choice
        required: true
        default: dev
        options:
          - dev
          - prod
      dry-run:
        type: boolean
        description: "Run a dry run with helm"
        required: false
        default: false
      debug:
        type: boolean
        description: "Run helm in debug mode"
        required: false
        default: false

jobs:
  determine_cloud_provider:
    uses: ./.github/workflows/_determine-provider.yml
    secrets: inherit

  deploy_gcp:
    uses: ./.github/workflows/_deploy-gke.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      app_name: subgraph-b
      cluster_suffix: ${{ inputs.environment }}
      dry-run: ${{ inputs.dry-run }}
      debug: ${{ inputs.debug }}

  deploy_aws:
    env:
      AWS: ${{ secrets.AWS_ACCESS_KEY }}
    if: "${{ env.AWS != '' }}"
    uses: ./.github/workflows/_deploy-aws.yml
    secrets: inherit
    with:
      version: ${{ inputs.version }}
      app_name: subgraph-b
      cluster_suffix: ${{ inputs.environment }}
      dry-run: ${{ inputs.dry-run }}
      debug: ${{ inputs.debug }}

  publish:
    needs: [deploy_aws, deploy_gcp]
    if: always() &&
      (needs.deploy_aws.result == 'success' || needs.deploy_aws.result == 'skipped') &&
      (needs.deploy_gcp.result == 'success' || needs.deploy_gcp.result == 'skipped')
    uses: ./.github/workflows/_rover-subgraph-publish.yml
    secrets: inherit
    with:
      subgraph_name: subgraph-b
      variant: dev
